# Generated by Django 4.1.2 on 2022-11-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_options'),
        ('produtoservico', '0001_initial'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='produto',
            field=models.ManyToManyField(through='produtoservico.ProdutoServico', to='produto.produto'),
        ),
    ]
