# Generated by Django 4.1.2 on 2022-11-22 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servico', '0001_initial'),
        ('produto', '0002_alter_produto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(help_text='Nome do produto', on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='produto.produto', verbose_name='produto')),
                ('servico', models.ForeignKey(help_text='Nome do serviço realizado', on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='servico.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Produto utilizado',
                'verbose_name_plural': 'Produtos utilizados',
            },
        ),
    ]
